version: '2'
services:
  webapp:
    container_name: metro-test
    build:
      context: ./
      dockerfile: Dockerfile-PHP
    volumes:
      - "../../:/var/www/html/"
    privileged: true
    working_dir: /var/www/html
    command: /usr/sbin/apache2ctl -D FOREGROUND


